#ifndef ADC_CFG_H
#define ADC_CFG_H

/*Options:
			ADC_CONTINUOUS_MODE_ENABLE
			ADC_CONTINUOUS_MODE_DISABLE
*/
#define ADC_CONTINUOUS_MODE		ADC_CONTINUOUS_MODE_ENABLE   

/*Options:
			ADC_DATA_RIGHT_ALIGNMENT
			ADC_DATA_LEFT_ALIGNMENT
*/
#define ADC_DATA_ALIGNMENT      ADC_DATA_RIGHT_ALIGNMENT  


#endif /*ADC_CFG_H*/
