#ifndef ULTRASONIC_PRIVATE_H
#deifne ULTRASONIC_PRIVATE_H


#define ULTRASONIC_PORTA	0
#define ULTRASONIC_PORTB	1
#define ULTRASONIC_PORTC 	2
#define ULTRASONIC_PORTD    3



#endif /*ULTRASONIC_PRIVATE_H*/
